# 变量引用减少重复代码
server: &server-ref
  host: INNER_INNER1
  user: root # default root
  port: 22 # default 22
  password: xxxxx
  privateKey: xxxxx
  privateKeyPathAuth: /path/to/file

version: v1.0.0
jobs:
  - name: 总局内部接入服务
    parameters:
      service: satc-access-inner
      environment: gd_inner
    steps:
      - name: Clone
        git:
          repo: git@gitee.com:guoxinliu/satc-platform.git
          branch: dev_xinjiang
      - name: Compile
        sh:
          - "cd satc-platform/satc-access-inner; make ENV=gd_inner"
      - name: Send package to Server
        scp:
          type: upload # upload or download
          servers:
            - <<: *server-ref
          remote: "/data/downloads"
      - name: Deploy
        cmd:
          servers:
            - <<: *server-ref
          cmd:
            - "cd satc-platform/satc-access-inner; make ENV=gd_inner"
