source:
  type: git # git : git repo, lfp : local file path
  git:
    repo: git@gitee.com:guoxinliu/satc-platform.git
    branch: dev_xinjiang
  lfp:

source-after:
  - "cd satc-platform/satc-access-inner; make ENV=gd_inner"

target-before:
  - ""
  - ""
target:
  servers:
    - INNER_INNER1
    - INNER_INNER2
  path:
    copy: /data/downloads
    deploy: /data/app
target-after:
  - ""
  - ""
