# 变量引用减少重复代码
server: &server-ref
  host: localhost
  user: you username # default root
  port: "22" # default 22
  type: password # password: 密码登陆, privateKey: 私钥字符串, privateKeyPath: 私钥路径
  password: you password
 privateKey: "xxxxx"
 privateKeyPath: /path/to/file

version: v1.0.0

jobs:
  - name: lenkins-test
    parameters:
      service_name: xxx_service
      environment: dev
    steps:
      - name: Clone
        git:
          repo: git@gitee.com:guoxinliu/lenkins.git
          branch: master
      - name: Compile
        sh:
          - "echo $PATH"
          - "mkdir -p git://bin"
          - "go build -o git://bin/lenkins"
      - name: Send package to Server
        scp:
          type: upload # upload or download
          servers:
            - <<: *server-ref
          remote: "/home/guoxin/Desktop/lenkins"
          local: "git://bin/lenkins"
      - name: Deploy
        cmd:
          servers:
            - <<: *server-ref
          cmd:
            - "pwd; cp /home/guoxin/Desktop/lenkins /home/guoxin/Desktop/lenkins-bin"
            - "/home/guoxin/Desktop/lenkins -h"
