# 变量引用减少重复代码
server: &server-ref
  host: localhost
  user: you username # default root
  port: "22" # default 22
  type: password # password: 密码登陆, privateKey: 私钥明文, privateKeyPath: 私钥路径
  # 密码登陆
  password: you password
  # 读取私钥明文；以明文的方式填写到配置文件中
  privateKey: "xxxxx"
  # 读取私钥路径；本机绝对路径或者用户目录下的SSH私钥
  # 1. 绝对路径 /path/to/id_rsa
  # 2. 读取用户目录下，例如： ~/path/to/id_rsa
  # 默认为 ~/.ssh/id_rsa
  privateKeyPath: /path/to/id_rsa

version: v1.0.0

jobs:
  - name: lenkins-test
    parameters:
      service_name: xxx_service
      environment: dev
    steps:
      - name: Clone
        git:
          repo: git@gitee.com:guoxinliu/lenkins.git
          branch: master
      - name: Compile
        sh:
          - "echo $PATH"
          - "mkdir -p git://bin"
          - "go build -o git://bin/lenkins"
      - name: Send package to Server
        scp:
          type: upload # upload or download
          servers:
            - <<: *server-ref
          remote: "/home/guoxin/Desktop/lenkins"
          local: "git://bin/lenkins"
      - name: Deploy
        cmd:
          servers:
            - <<: *server-ref
          cmd:
            - "pwd; cp /home/guoxin/Desktop/lenkins /home/guoxin/Desktop/lenkins-bin"
            - "/home/guoxin/Desktop/lenkins -h"
